spring.application.name=datronix

# ========== BASE DE DATOS (CON VARIABLES DE ENTORNO) ==========
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/datronix}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12131422}
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA / HIBERNATE ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========== SERVIDOR (opcional) ==========
# server.port=8080